# Generated by Django 4.2.6 on 2023-11-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_App', '0008_alter_blogdetail_more_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentreport',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='paymentreport',
            name='title',
        ),
    ]
