# Generated by Django 4.2.6 on 2023-11-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=0.0, upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('additional_info', models.TextField()),
                ('specifications1', models.CharField(blank=True, max_length=300, null=True)),
                ('specifications2', models.CharField(blank=True, max_length=300, null=True)),
                ('specifications3', models.CharField(blank=True, max_length=300, null=True)),
                ('specifications4', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField()),
                ('review_text', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_App.productdetail')),
            ],
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System_App.products'),
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('intro1', models.TextField()),
                ('intro2', models.TextField()),
                ('educational_year1', models.CharField(max_length=15)),
                ('school_year1', models.CharField(max_length=255)),
                ('description_year1', models.TextField()),
                ('educational_year2', models.CharField(blank=True, max_length=15, null=True)),
                ('school_year2', models.CharField(blank=True, max_length=255, null=True)),
                ('description_year2', models.TextField(blank=True, null=True)),
                ('educational_year3', models.CharField(blank=True, max_length=15, null=True)),
                ('school_year3', models.CharField(blank=True, max_length=255, null=True)),
                ('description_year3', models.TextField(blank=True, null=True)),
                ('educational_year4', models.CharField(blank=True, max_length=15, null=True)),
                ('school_year4', models.CharField(blank=True, max_length=255, null=True)),
                ('description_year4', models.TextField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('expertise_area1', models.CharField(max_length=255)),
                ('expertise_area2', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_area3', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_area4', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_area5', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_area6', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System_App.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_images/')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('service_feature1', models.CharField(max_length=255)),
                ('service_feature2', models.CharField(blank=True, max_length=255, null=True)),
                ('service_feature3', models.CharField(blank=True, max_length=255, null=True)),
                ('service_feature4', models.CharField(blank=True, max_length=255, null=True)),
                ('service_feature5', models.CharField(blank=True, max_length=255, null=True)),
                ('service_feature6', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System_App.department')),
            ],
        ),
    ]
