# Generated by Django 4.2.6 on 2023-11-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_App', '0004_paymentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreport',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='System_App.productdetail'),
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
