# Generated by Django 4.2.6 on 2023-11-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_App', '0005_paymentreport_product_paymentreport_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.CharField(max_length=500)),
                ('image', models.ImageField(default=0.0, upload_to='blog_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='System_App.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default=0.0, upload_to='comment_images/')),
                ('country', models.CharField(max_length=100)),
                ('date_posted', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System_App.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('intro_detail', models.TextField()),
                ('quote', models.CharField(max_length=500)),
                ('quote_expl', models.TextField()),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System_App.blog')),
            ],
        ),
    ]
