# Generated by Django 4.2.6 on 2023-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_App', '0006_blog_purchasedproduct_comment_blogdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='more_cont',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
