# Generated by Django 4.2.6 on 2023-11-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_App', '0009_remove_paymentreport_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('checkout_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_App.checkoutform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_App.products')),
            ],
        ),
        migrations.AddField(
            model_name='checkoutform',
            name='products',
            field=models.ManyToManyField(through='System_App.Purchase', to='System_App.products'),
        ),
    ]
