# Generated by Django 4.2.6 on 2023-11-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_App', '0010_purchase_checkoutform_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
